
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Alert } from 'react-native';

const getApiKey = async (): Promise<string | null> => {
    try {
        const apiKey = await AsyncStorage.getItem('apiKey');
        return apiKey;
    } catch (e) {
        console.error("Failed to load API key:", e);
        return null;
    }
};

export const generateCourseFromText = async (text: string): Promise<any> => {
    const apiKey = await getApiKey();
    if (!apiKey) {
        Alert.alert('API Key Not Found', 'Please set your Google Gemini API key in the settings.');
        return null;
    }

    const model = await AsyncStorage.getItem('aiModel') || 'gemini-1.5-flash';
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

    const prompt = `Based on the following text, generate a course structure with a title and a list of sections. Each section should have a title and a brief summary. Format the output as a JSON object with "title" and "sections" properties. The "sections" property should be an array of objects, each with "title" and "summary" properties.\n\nText: ${text}`;

    try {
        const response = await fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                contents: [{
                    parts: [{ text: prompt }]
                }]
            }),
        });

        const data = await response.json();
        if (data.candidates && data.candidates.length > 0) {
            const content = data.candidates[0].content.parts[0].text;
            // The response from the API is a JSON string, so we need to parse it.
            // I'll wrap this in a try-catch block to handle potential parsing errors.
            try {
                // The response might be wrapped in markdown, so I'll clean it up.
                const cleanedContent = content.replace(/```json/g, '').replace(/```/g, '').trim();
                return JSON.parse(cleanedContent);
            } catch (e) {
                console.error("Failed to parse course data:", e);
                Alert.alert('Error', 'Failed to parse the course structure from the AI response.');
                return null;
            }
        } else {
            console.error("No content generated by the API:", data);
            Alert.alert('Error', 'The AI did not generate a course structure. Please try again.');
            return null;
        }
    } catch (error) {
        console.error('Failed to generate course:', error);
        Alert.alert('Error', 'Failed to generate the course. Please check your internet connection and API key.');
        return null;
    }
};
